AppBundle\Entity\ProductPicture:
  productPicture{1..12}:
    path: "product<current()>.jpg"

AppBundle\Entity\Product:
  product{1..10}:
    name (unique): <sentence(2, true)>
    category: @category*
    description: <text(200)>
    pictures: 2x @productPicture*
    qty: <numberBetween(1, 100)>
    price: <randomFloat(2, 0, 100)>
    priceSpecial: <randomFloat(2, 0, $price)>
    rating: <randomFloat(2, 0, 5)>
    available: <randomElement(array ('0','1'))>
    createdAt: <dateTimeBetween('-1 years', 'now')>
    updatedAt: 30%? <dateTimeBetween($createdAt, 'now')>
    deletedAt: 5%? <dateTimeBetween($createdAt, 'now')>
