language: php

php:
  - 5.6

before_script:
  - composer self-update
  - composer install

script:
  - php app/console doctrine:database:create
  - php bin/phpunit -c app --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover