language: php

php:
  - 5.6

before_script:
  - composer self-update
  - composer install --dev --no-interaction --prefer-source
  - app/console cache:warmup --env=test --quiet

script:
  - php bin/phpunit -c app --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover