<?php

namespace AppBundle\Repository;

/**
 * AttributeOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributeOptionRepository extends \Doctrine\ORM\EntityRepository
{
}
