<?php

namespace AppBundle\Repository;

/**
 * InvoiceItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceItemsRepository extends \Doctrine\ORM\EntityRepository
{
}
