<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * InvoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceRepository extends EntityRepository
{
    public function getUserInvoices(User $user)
    {
        return $this->createQueryBuilder('i')
            ->select('i, s')
            ->leftJoin('i.statuses', 's')
            ->where('i.customer = :customer')
            ->addOrderBy('i.createdAt', 'desc')
            ->addOrderBy('s.createdAt', 'desc')
            ->setParameters(['customer' => $user])
            ->getQuery()
            ->getResult();
    }

    public function getInvoice($id)
    {
        return $this->createQueryBuilder('i')
            ->select('i, it, p, s')
            ->leftJoin('i.items', 'it')
            ->leftJoin('it.product', 'p')
            ->leftJoin('i.statuses', 's')
            ->where('i.id = :id')
            ->addOrderBy('s.createdAt', 'desc')
            ->setParameters(['id' => $id])
            ->getQuery()
            ->getSingleResult();
    }
}
