<?php

namespace AppBundle\Repository;

/**
 * InvoiceStatusesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceStatusesRepository extends \Doctrine\ORM\EntityRepository
{
}
