<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getAllQuery($search)
    {
        return $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.username like :username or u.email like :email or u.address like :address')
            ->setParameters(['username' => "%$search%", 'email' => "%$search%", 'address' => "%$search%"])
            ->getQuery();
    }
}
